spring.application.name=RestaurantMangement
server.port= 8081
database=h2

spring.profiles.active=posgres

# database init, supports mysql too
# spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

spring.jpa.defer-datasource-initialization=true
